#!/bin/bash
# my script

#make all

code0=0
code1=0
code2=0
code3=0
code4=0
code5=0
code6=0
code7=0
code8=0
code9=0
code10=0
code11=0
code12=0

for i in {1..4000}
do
	echo try nr. $i

	./app

	rv=$?

	echo Exit code: $rv

	if [ $rv -eq 0 ]
	then
		code0=$((code0+1))
	elif [ $rv -eq 1 ]
	then
		code1=$((code1+1))
	elif [ $rv -eq 2 ]
	then
		code2=$((code2+1))
	elif [ $rv -eq 3 ]
	then
		code3=$((code3+1))
	elif [ $rv -eq 4 ]
	then
		code4=$((code4+1))
	elif [ $rv -eq 5 ]
	then
		code5=$((code5+1))
	elif [ $rv -eq 6 ]
	then
		code6=$((code6+1))
	elif [ $rv -eq 7 ]
	then
		code7=$((code7+1))
	elif [ $rv -eq 8 ]
	then
		code8=$((code8+1))
	elif [ $rv -eq 9 ]
	then
		code9=$((code9+1))
	elif [ $rv -eq 10 ]
	then
		code10=$((code10+1))
	elif [ $rv -eq 11 ]
	then
		code11=$((code11+1))
	elif [ $rv -eq 12 ]
	then
		code12=$((code12+1))
	fi
done

echo Exit code 0: $code0
echo Exit code 1: $code1
echo Exit code 2: $code2
echo Exit code 3: $code3
echo Exit code 4: $code4
echo Exit code 5: $code5
echo Exit code 6: $code6
echo Exit code 7: $code7
echo Exit code 8: $code8
echo Exit code 9: $code9
echo Exit code 10: $code10
echo Exit code 11: $code11
echo Exit code 12: $code12